version: '3'

networks:
  laravel:


services:
  nginx:
    container_name: nginx
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "99:80"
    volumes:
      - ./contents:/var/www/html:delegated
    depends_on:
      - php 
      - mysql
    networks:
      - laravel

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: linebot
      MYSQL_USER: hivanmanh
      MYSQL_PASSWORD: hivanmanh
      MYSQL_ROOT_PASSWORD: hivanmanh
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  app:
    container_name: app
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./contents:/var/www/html:delegated
    working_dir: /var/www/html
    tty: true
    entrypoint: 
      - sh
      - -c
      - |
        composer install &&
        php artisan migrate:refresh --seed &&
        php-fpm -y /usr/local/etc/php-fpm.conf -R
    networks:
      - laravel

  rector:
    container_name: rector
    build:
      context: ./docker
      dockerfile: rector.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes: 
      - ./contents:/var/www/html
    working_dir: /var/www/html
    depends_on: 
      - php  
    # entrypoint: ["tail", "-f", "/dev/null"]
    tty: true
    entrypoint: 
      - sh
      - -c
      - |
        cd tools/rector &&
        composer install &&
        tail -f /dev/null
    # entrypoint: ["sh", "-c", "cd tools/rector && composer install && while true; do sleep 86400; done"]
    networks:
      - laravel
      
  client:
    image: node:18.14.2
    container_name: client
    volumes:
      - ./contents/client:/var/www/html/client:delegated
    ports:
      - "8089:8080"
    working_dir: /var/www/html/client/
    entrypoint: 
      - sh
      - -c
      - |
        npm install &&
        npm run serve &&
        tail -f /dev/null
    networks:
      - laravel

  l5-swagger-app:
    image: l5-swagger-app
    container_name: swagger
    restart: "no"
    build:
      args:
        user: l5-swagger
        uid: 1000
      context: ./docker
      dockerfile: swagger.dockerfile
      target: local
    volumes:
      - ./contents:/app/l5-swagger-app:rw
    ports:
      - "7777:80"
    depends_on:
      - mysql
      - app
      - rector
      - client
    networks:
      - laravel
